import { useState } from 'react'
import { BlockMath, InlineMath } from 'react-katex'
import 'katex/dist/katex.min.css'
import DefinitionBlock from '../../../components/content/DefinitionBlock.jsx'
import ExampleBlock from '../../../components/content/ExampleBlock.jsx'
import NoteBlock from '../../../components/content/NoteBlock.jsx'
import WarningBlock from '../../../components/content/WarningBlock.jsx'
import PythonCode from '../../../components/content/PythonCode.jsx'

function VideoLLMComparison() {
  const [selected, setSelected] = useState('videoclip')

  const models = {
    videoclip: { name: 'VideoCLIP', approach: 'Contrastive', vision: 'TimeSformer', text: 'CLIP text encoder', training: 'Video-text contrastive alignment', tasks: 'Retrieval, zero-shot classification' },
    videollava: { name: 'Video-LLaVA', approach: 'Generative', vision: 'ViT + LanguageBind', text: 'Vicuna-7B', training: 'Visual instruction tuning', tasks: 'Video QA, captioning, reasoning' },
    videochat: { name: 'VideoChat', approach: 'Generative', vision: 'ViT-G/14', text: 'StableLM / LLaMA', training: 'Video instruction tuning + chat', tasks: 'Conversational video understanding' },
    internvideo: { name: 'InternVideo2', approach: 'Hybrid', vision: 'ViT-6B', text: 'InternLM', training: 'Multimodal masked + contrastive + generative', tasks: 'All video tasks + generation' },
  }

  const m = models[selected]

  return (
    <div className="my-6 rounded-xl border border-gray-200 bg-white p-6 shadow-sm dark:border-gray-700 dark:bg-gray-900/50">
      <h3 className="mb-3 text-base font-bold text-gray-800 dark:text-gray-200">Video-Language Models</h3>
      <div className="flex flex-wrap gap-2 mb-4">
        {Object.entries(models).map(([key, val]) => (
          <button key={key} onClick={() => setSelected(key)}
            className={`rounded-lg px-3 py-1.5 text-sm font-medium transition-colors ${selected === key ? 'bg-violet-600 text-white' : 'bg-gray-100 text-gray-600 hover:bg-violet-100 dark:bg-gray-800 dark:text-gray-400'}`}>
            {val.name}
          </button>
        ))}
      </div>
      <div className="grid grid-cols-2 gap-3 text-sm">
        {[['Approach', m.approach], ['Vision encoder', m.vision], ['Language model', m.text],
          ['Training', m.training], ['Tasks', m.tasks]
        ].map(([label, val]) => (
          <div key={label} className={`rounded-lg bg-violet-50 dark:bg-violet-900/20 p-3 ${label === 'Tasks' ? 'col-span-2' : ''}`}>
            <p className="text-xs text-violet-600 dark:text-violet-400 font-semibold">{label}</p>
            <p className="text-gray-700 dark:text-gray-300">{val}</p>
          </div>
        ))}
      </div>
    </div>
  )
}

export default function VideoLanguageModels() {
  return (
    <div className="space-y-6">
      <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
        Video-language models extend multimodal LLMs to understand temporal dynamics, enabling
        video question answering, dense captioning, and temporal grounding through natural
        language interaction with video content.
      </p>

      <DefinitionBlock title="Video-Language Alignment">
        <p>Contrastive video-language models learn a shared embedding space:</p>
        <BlockMath math="\mathcal{L} = -\frac{1}{B}\sum_{i=1}^{B}\left[\log \frac{e^{\text{sim}(v_i, t_i)/\tau}}{\sum_j e^{\text{sim}(v_i, t_j)/\tau}} + \log \frac{e^{\text{sim}(t_i, v_i)/\tau}}{\sum_j e^{\text{sim}(t_i, v_j)/\tau}}\right]" />
        <p className="mt-2">
          Video features <InlineMath math="v_i" /> aggregate temporal information (e.g., mean pooling
          frame embeddings), while text features <InlineMath math="t_i" /> come from a text encoder.
          This enables zero-shot video retrieval and classification.
        </p>
      </DefinitionBlock>

      <VideoLLMComparison />

      <ExampleBlock title="Visual Instruction Tuning for Video">
        <p>
          Video-LLaVA adapts the LLaVA framework to video by projecting frame tokens into the
          LLM's embedding space:
        </p>
        <BlockMath math="h_\text{video} = W_\text{proj} \cdot \text{Concat}[f_1, f_2, \ldots, f_T]" />
        <p className="mt-1">
          The projected video tokens are prepended to text tokens, and the LLM generates
          responses autoregressively. Training uses video instruction-following datasets
          generated by GPT-4V or human annotators.
        </p>
      </ExampleBlock>

      <PythonCode
        title="Video-Language Model Architecture"
        code={`import torch
import torch.nn as nn

class SimpleVideoLLM(nn.Module):
    def __init__(self, vis_dim=768, llm_dim=4096, num_frames=8, vocab_size=32000):
        super().__init__()
        # Vision encoder (frozen ViT)
        self.vis_encoder = nn.Sequential(
            nn.Linear(3 * 224 * 224, vis_dim),  # simplified
            nn.LayerNorm(vis_dim),
        )
        # Projection: vision -> LLM space
        self.vis_proj = nn.Sequential(
            nn.Linear(vis_dim, llm_dim),
            nn.GELU(),
            nn.Linear(llm_dim, llm_dim),
        )
        # Temporal aggregation
        self.temporal_attn = nn.MultiheadAttention(llm_dim, 8, batch_first=True)
        # LLM decoder (simplified)
        self.llm = nn.TransformerDecoder(
            nn.TransformerDecoderLayer(d_model=llm_dim, nhead=8, batch_first=True),
            num_layers=2
        )
        self.text_embed = nn.Embedding(vocab_size, llm_dim)
        self.output_head = nn.Linear(llm_dim, vocab_size)

    def encode_video(self, frames):
        B, T = frames.shape[:2]
        # Encode each frame
        flat = frames.view(B * T, -1)
        vis_tokens = self.vis_encoder(flat).view(B, T, -1)
        # Project to LLM space
        projected = self.vis_proj(vis_tokens)
        # Temporal aggregation
        temporal_out, _ = self.temporal_attn(projected, projected, projected)
        return temporal_out

    def forward(self, frames, text_ids):
        video_tokens = self.encode_video(frames)  # [B, T, llm_dim]
        text_tokens = self.text_embed(text_ids)    # [B, L, llm_dim]
        # Cross-attend text to video
        output = self.llm(text_tokens, video_tokens)
        return self.output_head(output)

model = SimpleVideoLLM()
frames = torch.randn(2, 8, 3, 224, 224)
question = torch.randint(0, 32000, (2, 20))
logits = model(frames, question)
print(f"Output logits: {logits.shape}")  # [2, 20, 32000]`}
      />

      <WarningBlock title="Temporal Grounding Challenge">
        <p>
          Current video LLMs struggle with precise temporal reasoning (e.g., "What happened
          at the 30-second mark?"). Uniform frame sampling loses temporal precision, and most
          models cannot process full-length videos. Active research areas include hierarchical
          video encoding, timestamp-aware tokens, and streaming video processing.
        </p>
      </WarningBlock>

      <NoteBlock type="note" title="Long Video Understanding">
        <p>
          Understanding hour-long videos requires new architectures. Approaches include
          <strong>memory banks</strong> that cache past context, <strong>hierarchical encoding</strong> at
          multiple temporal scales, and <strong>retrieval-augmented</strong> methods that select relevant
          clips. Models like MovieChat and LongViViT address this challenge, but efficient
          long-video understanding remains largely unsolved.
        </p>
      </NoteBlock>
    </div>
  )
}
